
TICKER_MAPPINGS = {
    "Adani Enterprises": "ADANIENT",
    "Adani Ports and Special Economic Zone": "ADANIPORTS",
    "Apollo Hospitals Enterprise": "APOLLOHOSP",
    "Asian Paints": "ASIANPAINT",
    "Axis Bank": "AXISBANK",
    "Bajaj Auto": "BAJAJ-AUTO",
    "Bajaj Finance": "BAJFINANCE",
    "Bajaj Finserv": "BAJAJFINSV",
    "Bharat Electronics": "BEL",
    "Bharat Petroleum Corporation": "BPCL",
    "Bharti Airtel": "BHARTIARTL",
    "Britannia Industries": "BRITANNIA",
    "Cipla": "CIPLA",
    "Coal India": "COALINDIA",
    "Dr. Reddy's Laboratories": "DRREDDY",
    "Eicher Motors": "EICHERMOT",
    "Grasim Industries": "GRASIM",
    "HCL Technologies": "HCLTECH",
    "HDFC Bank": "HDFCBANK",
    "HDFC Life Insurance": "HDFCLIFE",
    "Hero MotoCorp": "HEROMOTOCO",
    "Hindalco Industries": "HINDALCO",
    "Hindustan Unilever": "HINDUNILVR",
    "ICICI Bank": "ICICIBANK",
    "IndusInd Bank": "INDUSINDBK",
    "Infosys": "INFY",
    "ITC": "ITC",
    "JSW Steel": "JSWSTEEL",
    "Kotak Mahindra Bank": "KOTAKBANK",
    "Larsen & Toubro": "LT",
    "Mahindra & Mahindra": "M&M",
    "Maruti Suzuki India": "MARUTI",
    "Nestle India": "NESTLEIND",
    "NTPC": "NTPC",
    "Oil and Natural Gas Corporation": "ONGC",
    "Power Grid Corporation of India": "POWERGRID",
    "Reliance Industries": "RELIANCE",
    "SBI Life Insurance": "SBILIFE",
    "Shriram Finance": "SHRIRAMFIN",
    "State Bank of India": "SBIN",
    "Sun Pharmaceutical Industries": "SUNPHARMA",
    "Tata Consultancy Services": "TCS",
    "Tata Consumer Products": "TATACONSUM",
    "Tata Motors": "TATAMOTORS",
    "Tata Steel": "TATASTEEL",
    "Tech Mahindra": "TECHM",
    "Titan Company": "TITAN",
    "Trent": "TRENT",
    "UltraTech Cement": "ULTRACEMCO",
    "Wipro": "WIPRO",
    "SBI": "SBIN"
}